version: '3.3'
services:
  #MySQL Service
  mysql_db:
    #image: mariadb
    image: mysql:5.7.22
    command: --ssl=0
    container_name: mysql_db
    restart: always
    volumes:
      - ./dbdata:/var/lib/mysql:z
      - ./config/my.cnf:/etc/mysql/my.cnf:z
      - ./log:/var/log/mysql:z
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: mysql_user
      MYSQL_DATABASE: mysql_database
      MYSQL_USER_HOST: '%'
      MYSQL_PASSWORD: qwert123
      MYSQL_ROOT_PASSWORD: qwert123